# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: lrocigno <lrocigno@student.42sp.org>       +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2021/02/16 12:00:43 by lrocigno          #+#    #+#              #
#    Updated: 2021/04/01 21:33:48 by lrocigno         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = libft.a

CC = gcc

FLAGS = -Wall -Wextra -Werror

ARCHV = ar -rcs

HEADER = libft.h

HEADER_PATH = ../headers/

SRC =	ft_memset.c \
		ft_bzero.c \
		ft_memcpy.c \
		ft_memccpy.c \
		ft_memmove.c \
		ft_memchr.c \
		ft_memcmp.c \
		ft_strlen.c \
		ft_strlcpy.c \
		ft_strlcat.c \
		ft_strchr.c \
		ft_strrchr.c \
		ft_strnstr.c \
		ft_strncmp.c \
		ft_atoi.c \
		ft_isalpha.c \
		ft_isdigit.c \
		ft_isalnum.c \
		ft_isascii.c \
		ft_isprint.c \
		ft_toupper.c \
		ft_tolower.c \
		ft_calloc.c \
		ft_strdup.c \
		ft_substr.c \
		ft_strjoin.c \
		ft_strtrim.c \
		ft_split.c \
		ft_itoa.c \
		ft_strmapi.c \
		ft_putchar_fd.c \
		ft_putstr_fd.c \
		ft_putendl_fd.c \
		ft_putnbr_fd.c \
		ft_lstnew.c \
		ft_lstadd_front.c \
		ft_lstsize.c \
		ft_lstlast.c \
		ft_lstadd_back.c \
		ft_lstdelone.c \
		ft_lstclear.c \
		ft_lstiter.c \
		ft_lstmap.c \
		ft_dtox.c \
		ft_reallocncat.c \
		ft_strhvchr.c \

SRC_PATH = ./src

SRC_FULL = $(addprefix $(SRC_PATH)/,$(SRC))

OUT = $(SRC:%.c=%.o)

OUT_PATH = ./out

OUT_FULL = $(addprefix $(OUT_PATH)/,$(OUT))

$(NAME): $(OUT_FULL)
	$(ARCHV) $(NAME) $(OUT_FULL)

$(OUT_PATH)/%.o: $(SRC_PATH)/%.c
	mkdir -p $(OUT_PATH)
	$(CC) $(FLAGS) -I $(HEADER_PATH) -o $@ -c $<

all: $(NAME)

clean: 
	rm -rf ./out

fclean: clean
	rm -f $(NAME)

re: fclean all

.PHONY: clean fclean all re
